table Fact_ParqueVehicular
	lineageTag: 34c2704b-a374-4530-a807-1f923e57b77c

	measure 'Vehículos autorizados' = VAR AnioEvaluado = MAX('Dim_Año'[Año]) RETURN CALCULATE(SUM(Fact_ParqueVehicular[VehiculosAutorizados]), KEEPFILTERS('Dim_Año'[Año] = AnioEvaluado))
		formatString: #,0
		lineageTag: 86f81a84-8878-4771-8fa2-e0bec96c5c83

	measure 'Vehículos por empresa' = DIVIDE([Vehículos autorizados], [Total empresas autorizadas])
		formatString: 0.00
		lineageTag: 3813cc39-0157-4429-8527-a4fb0eedf053

	measure 'Vehículos ranking' =
			
			VAR Categoria =
			    SELECTEDVALUE(Ranking_Departamento[DepartamentoRanking])
			
			VAR DepartamentosVisibles =
			    ALLSELECTED(Dim_Departamento[Departamento])
			
			VAR Top10Departamentos =
			    TOPN(
			        10,
			        DepartamentosVisibles,
			        [Vehículos autorizados], DESC,
			        Dim_Departamento[Departamento], ASC
			    )
			
			VAR EsTop10 =
			    CONTAINS(
			        Top10Departamentos,
			        Dim_Departamento[Departamento],
			        Categoria
			    )
			
			RETURN
			    SWITCH(
			        TRUE(),
			
			        Categoria = "Otros departamentos",
			            CALCULATE(
			                [Vehículos autorizados],
			                KEEPFILTERS(
			                    EXCEPT(
			                        DepartamentosVisibles,
			                        Top10Departamentos
			                    )
			                )
			            ),
			
			        EsTop10,
			            CALCULATE(
			                [Vehículos autorizados],
			                KEEPFILTERS(
			                    TREATAS(
			                        {Categoria},
			                        Dim_Departamento[Departamento]
			                    )
			                )
			            ),
			
			        BLANK()
			    )
		formatString: #,0
		lineageTag: 79511763-eac8-4ef1-9428-7ab75e4e201c

	measure 'Etiqueta parque extremos' =
			
			VAR AnioActual =
			    SELECTEDVALUE('Dim_Año'[Año])
			RETURN
			    IF(
			        AnioActual IN { 2016, 2025 },
			        [Vehículos autorizados],
			        BLANK()
			    )
		formatString: #,0
		lineageTag: f4b468a0-b09c-4a1c-b66f-d09154917814

	column DEPARTAMENTO
		dataType: string
		lineageTag: 29e4ef41-3429-4f59-becd-efa9838341d9
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 8e8b9af9-6b37-4a97-a6f7-bd7fd4124253
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column VehiculosAutorizados
		dataType: int64
		formatString: 0
		lineageTag: bb3236e3-aa10-4a5b-b076-068e8d5fdfea
		summarizeBy: sum
		sourceColumn: VehiculosAutorizados

		annotation SummarizationSetBy = Automatic

	partition Fact_ParqueVehicular = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(pURL_ParqueVehicular), null, true),
				    C.1.3.13_Sheet = Origen{[Item="C.1.3.13",Kind="Sheet"]}[Data],
				    #"Filas superiores quitadas" = Table.Skip(C.1.3.13_Sheet,2),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas superiores quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"DEPARTAMENTO", type text}, {"2016", Int64.Type}, {"2017", Int64.Type}, {"2018", Int64.Type}, {"2019", Int64.Type}, {"2020", Int64.Type}, {"2021", Int64.Type}, {"2022", Int64.Type}, {"2023", Int64.Type}, {"2024", Int64.Type}, {"2025", Int64.Type}}),
				    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado", {"DEPARTAMENTO"}, "Atributo", "Valor"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Otras columnas con anulación de dinamización",{{"Atributo", Int64.Type}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado1",{{"Atributo", "Año"}, {"Valor", "VehiculosAutorizados"}}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas con nombre cambiado", each ([DEPARTAMENTO] <> "TOTAL")),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","Ancash","Áncash",Replacer.ReplaceText,{"DEPARTAMENTO"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Cuzco","Cusco",Replacer.ReplaceText,{"DEPARTAMENTO"})
				in
				    #"Valor reemplazado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

